### ISSUE TITLE
gulp-util is deprecated - replace it

### ISSUE THREAD

**Issue by dewrox** [kevva/gulp-decompress#18]
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by demurgos** [comment]
[`gulp-decompress` does not depend on `gulp-util`](https://www.npmjs.com/package/gulp-decompress).

This dependency was removed [6 months ago](https://github.com/kevva/gulp-decompress/pull/13). This issue is a duplicate of the last 4 issues: #12, #14, #15, #16.

Please close this issue and be more careful in the future when reporting issues.
